/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.22                       *
*        Compiled Jul  4 2013, 12:18:44                              *
*        (C) 1998 - 2013 Segger Microcontroller GmbH & Co. KG
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: songti20.c                                            *
* Font:        微软雅黑                                              *
* Height:      36                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  36                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: D:\私活\枪\战舰V3 资料盘(A盘)\6，软件资料\3，EMWIN学习资料\emWin5.26源码\emWin\Tool\cc.txt*
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontsongti20;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_Fontsongti20_0020[  1] = { /* code 0020, SPACE */
  ________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti20_0030[ 40] = { /* code 0030, DIGIT ZERO */
  _____XXX,XXX_____,
  ___XXXXX,XXXX____,
  __XXXXXX,XXXXX___,
  _XXXXX__,_XXXXX__,
  _XXXX___,__XXXX__,
  _XXXX___,__XXXXX_,
  XXXX____,___XXXX_,
  XXXX____,___XXXX_,
  XXXX____,___XXXX_,
  XXXX____,___XXXX_,
  XXXX____,___XXXX_,
  XXXX____,___XXXX_,
  XXXX____,___XXXX_,
  XXXX____,___XXXX_,
  XXXXX___,__XXXX__,
  _XXXX___,__XXXX__,
  _XXXXX__,_XXXXX__,
  __XXXXXX,XXXXX___,
  ___XXXXX,XXXX____,
  ____XXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti20_0031[ 40] = { /* code 0031, DIGIT ONE */
  _____XXX,________,
  XXXXXXXX,________,
  XXXXXXXX,________,
  XXXXXXXX,________,
  XX__XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  ____XXXX,________,
  XXXXXXXX,XXXX____,
  XXXXXXXX,XXXX____,
  XXXXXXXX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti20_0032[ 40] = { /* code 0032, DIGIT TWO */
  ___XXXXX,XX______,
  _XXXXXXX,XXX_____,
  _XXXXXXX,XXXX____,
  _XX_____,XXXXX___,
  _X______,_XXXX___,
  ________,_XXXX___,
  ________,_XXXX___,
  ________,_XXXX___,
  ________,XXXX____,
  ________,XXXX____,
  _______X,XXX_____,
  ______XX,XX______,
  _____XXX,X_______,
  ____XXXX,________,
  ___XXXX_,________,
  __XXXX__,________,
  _XXXX___,________,
  XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti20_0033[ 40] = { /* code 0033, DIGIT THREE */
  __XXXXXX,X_______,
  _XXXXXXX,XXX_____,
  _XXXXXXX,XXX_____,
  _X_____X,XXXX____,
  ________,XXXX____,
  ________,XXXX____,
  ________,XXXX____,
  _______X,XXX_____,
  __XXXXXX,XX______,
  __XXXXXX,X_______,
  __XXXXXX,XXX_____,
  _______X,XXXX____,
  ________,_XXXX___,
  ________,_XXXX___,
  ________,_XXXX___,
  X_______,_XXXX___,
  XX_____X,XXXX____,
  XXXXXXXX,XXXX____,
  XXXXXXXX,XXX_____,
  _XXXXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti20_0034[ 40] = { /* code 0034, DIGIT FOUR */
  ________,XXXXX___,
  ________,XXXXX___,
  _______X,XXXXX___,
  ______XX,XXXXX___,
  ______XX,XXXXX___,
  _____XXX,_XXXX___,
  ____XXXX,_XXXX___,
  ____XXX_,_XXXX___,
  ___XXX__,_XXXX___,
  __XXXX__,_XXXX___,
  __XXX___,_XXXX___,
  _XXXX___,_XXXX___,
  _XXX____,_XXXX___,
  XXXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXXX_,
  ________,_XXXX___,
  ________,_XXXX___,
  ________,_XXXX___,
  ________,_XXXX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti20_0035[ 40] = { /* code 0035, DIGIT FIVE */
  _XXXXXXX,XXXX____,
  _XXXXXXX,XXXX____,
  _XXXXXXX,XXXX____,
  _XXXX___,________,
  _XXXX___,________,
  _XXXX___,________,
  _XXXX___,________,
  _XXXXXXX,XX______,
  _XXXXXXX,XXX_____,
  _XXXXXXX,XXXX____,
  _______X,XXXXX___,
  ________,XXXXX___,
  ________,_XXXX___,
  ________,_XXXX___,
  ________,_XXXX___,
  ________,XXXXX___,
  X______X,XXXX____,
  XXXXXXXX,XXX_____,
  XXXXXXXX,XX______,
  _XXXXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti20_0036[ 40] = { /* code 0036, DIGIT SIX */
  _______X,XXXXXX__,
  ____XXXX,XXXXXX__,
  ___XXXXX,XXXXXX__,
  __XXXXX_,_____X__,
  __XXXX__,________,
  _XXXX___,________,
  _XXX____,________,
  XXXX__XX,XXXX____,
  XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXXX__,
  XXXXXX__,__XXXXX_,
  XXXX____,___XXXX_,
  XXXX____,___XXXX_,
  XXXX____,___XXXX_,
  XXXX____,___XXXX_,
  _XXXX___,__XXXXX_,
  _XXXXX__,_XXXXX__,
  __XXXXXX,XXXXX___,
  ___XXXXX,XXXX____,
  _____XXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti20_0037[ 40] = { /* code 0037, DIGIT SEVEN */
  XXXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXXX_,
  ________,__XXXX__,
  ________,_XXXXX__,
  ________,_XXXXX__,
  ________,_XXXX___,
  ________,XXXXX___,
  ________,XXXX____,
  _______X,XXXX____,
  _______X,XXXX____,
  ______XX,XXX_____,
  ______XX,XXX_____,
  ______XX,XX______,
  _____XXX,XX______,
  _____XXX,XX______,
  ____XXXX,X_______,
  ____XXXX,X_______,
  ___XXXXX,________,
  ___XXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti20_0038[ 40] = { /* code 0038, DIGIT EIGHT */
  _____XXX,XXX_____,
  ___XXXXX,XXXX____,
  __XXXXXX,XXXXX___,
  _XXXXX__,_XXXXX__,
  _XXXX___,__XXXX__,
  _XXXX___,__XXXX__,
  _XXXX___,__XXXX__,
  __XXXXX_,_XXXX___,
  ___XXXXX,XXXX____,
  _____XXX,XXX_____,
  ___XXXXX,XXXXX___,
  _XXXXX__,_XXXXX__,
  _XXXX___,__XXXXX_,
  XXXX____,___XXXX_,
  XXXX____,___XXXX_,
  XXXX____,___XXXX_,
  XXXXX___,__XXXXX_,
  _XXXXXXX,XXXXXX__,
  __XXXXXX,XXXXX___,
  ____XXXX,XXX_____};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti20_0039[ 40] = { /* code 0039, DIGIT NINE */
  ____XXXX,XX______,
  __XXXXXX,XXX_____,
  _XXXXXXX,XXXX____,
  _XXXX___,_XXXX___,
  XXXX____,_XXXX___,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXX____,__XXXX__,
  XXXXX___,_XXXXX__,
  _XXXXXXX,XXXXXX__,
  __XXXXXX,XXXXXX__,
  ___XXXXX,X_XXXX__,
  ________,__XXX___,
  ________,_XXXX___,
  ________,_XXXX___,
  _X______,XXXX____,
  _XXXXXXX,XXX_____,
  _XXXXXXX,XX______,
  __XXXXXX,________};

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_Fontsongti20_4EBA[104] = { /* code 4EBA */
  ________,____XXX_,________,________,
  ________,____XXX_,________,________,
  ________,___XXXX_,________,________,
  ________,___XXXX_,________,________,
  ________,___XXXX_,________,________,
  ________,___XXXX_,________,________,
  ________,___XXXX_,________,________,
  ________,___XXXX_,________,________,
  ________,___XXXXX,________,________,
  ________,___XXXXX,________,________,
  ________,__XXXXXX,________,________,
  ________,__XXXXXX,________,________,
  ________,__XXXXXX,X_______,________,
  ________,_XXXX_XX,X_______,________,
  ________,_XXXX_XX,XX______,________,
  ________,XXXXX_XX,XX______,________,
  ________,XXXX___X,XXX_____,________,
  _______X,XXXX___X,XXX_____,________,
  ______XX,XXX_____,XXXX____,________,
  _____XXX,XX______,XXXXX___,________,
  ____XXXX,X_______,_XXXXX__,________,
  ___XXXXX,X_______,__XXXXX_,________,
  __XXXXXX,________,___XXXXX,X_______,
  _XXXXX__,________,____XXXX,XX______,
  __XXX___,________,_____XXX,X_______,
  ___X____,________,_______X,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti20_5934[104] = { /* code 5934 */
  _____X__,_____XXX,X_______,________,
  ____XXXX,_____XXX,X_______,________,
  _____XXX,XXX__XXX,X_______,________,
  ______XX,XXXX_XXX,X_______,________,
  ________,XXX__XXX,X_______,________,
  __X_____,_X___XXX,X_______,________,
  __XXX___,_____XXX,X_______,________,
  _XXXXXX_,_____XXX,X_______,________,
  __XXXXXX,_____XXX,X_______,________,
  ____XXXX,X____XXX,X_______,________,
  _____XXX,X____XXX,X_______,________,
  _______X,_____XXX,X_______,________,
  ________,_____XXX,X_______,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,X_______,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,X_______,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,X_______,
  ________,___XXXXX,________,________,
  ________,___XXXXX,________,________,
  ________,__XXXXXX,XX______,________,
  ________,_XXXXXXX,XXX_____,________,
  _______X,XXXXX_XX,XXXXX___,________,
  _____XXX,XXXX____,XXXXXXX_,________,
  __XXXXXX,XX______,_XXXXXXX,________,
  XXXXXXXX,X_______,___XXXXX,X_______,
  _XXXXX__,________,_____XXX,________,
  __XX____,________,______X_,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti20_5F39[104] = { /* code 5F39 */
  ________,_____X__,____XX__,________,
  XXXXXXXX,___XXXX_,____XXXX,________,
  XXXXXXXX,____XXXX,___XXXX_,________,
  XXXXXXXX,____XXXX,___XXX__,________,
  _____XXX,_XXXXXXX,XXXXXXXX,X_______,
  _____XXX,_XXXXXXX,XXXXXXXX,X_______,
  _____XXX,_XXXXXXX,XXXXXXXX,X_______,
  _____XXX,_XXXX__X,XXX__XXX,X_______,
  XXXXXXXX,_XXXX__X,XXX__XXX,X_______,
  XXXXXXXX,_XXXXXXX,XXXXXXXX,X_______,
  XXXXXXXX,_XXXXXXX,XXXXXXXX,X_______,
  XXX_____,_XXXXXXX,XXXXXXXX,X_______,
  XXX_____,_XXXX__X,XXX__XXX,X_______,
  XXX_____,_XXXX__X,XXX__XXX,X_______,
  XXX_____,_XXXXXXX,XXXXXXXX,X_______,
  XXXXXXXX,_XXXXXXX,XXXXXXXX,X_______,
  XXXXXXXX,_XXXXXXX,XXXXXXXX,X_______,
  XXXXXXXX,_______X,XXX_____,________,
  ____XXXX,_______X,XXX_____,________,
  ____XXXX,_XXXXXXX,XXXXXXXX,XX______,
  ____XXXX,_XXXXXXX,XXXXXXXX,XX______,
  ____XXXX,_XXXXXXX,XXXXXXXX,XX______,
  ____XXX_,_______X,XXX_____,________,
  XXXXXXX_,_______X,XXX_____,________,
  XXXXXXX_,_______X,XXX_____,________,
  XXXXXX__,_______X,XXX_____,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti20_6211[104] = { /* code 6211 */
  ________,______XX,XX______,________,
  ________,XXXX__XX,XX__X___,________,
  _XXXXXXX,XXXXX_XX,XX_XXXX_,________,
  _XXXXXXX,XXXXX_XX,XXXXXXXX,________,
  _XXXXXXX,XXX___XX,XX__XXXX,X_______,
  _____XXX,X_____XX,XX___XXX,________,
  _____XXX,X_____XX,XX____X_,________,
  _____XXX,X_____XX,XX______,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  _____XXX,X_____XX,XX______,________,
  _____XXX,X_____XX,XX____X_,________,
  _____XXX,X__XXX_X,XX____XX,X_______,
  ____XXXX,XXXXX__X,XX___XXX,X_______,
  XXXXXXXX,XXXXX__X,XX__XXXX,________,
  _XXXXXXX,X______X,XXXXXXXX,________,
  _XX__XXX,X______X,XXXXXXX_,________,
  _____XXX,X______X,XXXXX__X,________,
  _____XXX,X______X,XXXX___X,XX______,
  _____XXX,X____XXX,XXXX___X,XXX_____,
  _____XXX,X__XXXXX,XXXX___X,XX______,
  _____XXX,X_XXXXXX,_XXXX__X,XX______,
  _XXXXXXX,X__XXXX_,_XXXXXXX,XX______,
  __XXXXXX,X___X___,__XXXXXX,X_______,
  __XXXXXX,________,____XXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti20_654C[104] = { /* code 654C */
  ________,________,XX______,________,
  ________,XXXXX___,XXXX____,________,
  _XXXXXXX,XXXXX___,XXX_____,________,
  _XXXXXXX,XXXXX__X,XXX_____,________,
  _XXXXXXX,X______X,XXXXXXXX,XXX_____,
  _____XXX,X______X,XXXXXXXX,XXX_____,
  _____XXX,X_____XX,XXXXXXXX,XXX_____,
  XXXXXXXX,XXXXX_XX,X_____XX,X_______,
  XXXXXXXX,XXXXXXXX,X_____XX,X_______,
  XXXXXXXX,XXXXXXXX,XX___XXX,X_______,
  _____XXX,X___XXXX,XX___XXX,X_______,
  _____XXX,X____XXX,XX___XXX,________,
  _____XXX,X_____XX,XX___XXX,________,
  _XXXXXXX,XXXXX__X,XX__XXXX,________,
  _XXXXXXX,XXXXX___,XXX_XXXX,________,
  _XXXXXXX,XXXXX___,XXX_XXX_,________,
  _XXXX___,_XXXX___,XXXXXXX_,________,
  _XXXX___,_XXXX___,_XXXXX__,________,
  _XXXX___,_XXXX___,_XXXXX__,________,
  _XXXX___,_XXXX___,_XXXXX__,________,
  _XXXX___,_XXXX___,XXXXXXX_,________,
  _XXXXXXX,XXXXX_XX,XXXXXXXX,________,
  _XXXXXXX,XXXXXXXX,XXX_XXXX,XX______,
  _XXXXXXX,XXXXXXXX,XX___XXX,XX______,
  _XXXX___,_XXXXXXX,______XX,XX______,
  _XXXX___,_XXXX_X_,________,X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti20_65B9[104] = { /* code 65B9 */
  ________,_____XX_,________,________,
  ________,___XXXXX,________,________,
  ________,___XXXXX,________,________,
  ________,____XXXX,________,________,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  _______X,XXX_____,________,________,
  _______X,XXX_____,________,________,
  _______X,XXX_____,________,________,
  _______X,XXX_____,________,________,
  _______X,XXXXXXXX,XXXXXXX_,________,
  _______X,XXXXXXXX,XXXXXXX_,________,
  _______X,XXXXXXXX,XXXXXXX_,________,
  _______X,XXX_____,___XXXX_,________,
  ______XX,XX______,___XXXX_,________,
  ______XX,XX______,___XXXX_,________,
  ______XX,XX______,___XXXX_,________,
  _____XXX,XX______,___XXXX_,________,
  ____XXXX,X_______,___XXXX_,________,
  ____XXXX,X_______,___XXXX_,________,
  ___XXXXX,________,__XXXXX_,________,
  _XXXXXX_,____XXXX,XXXXXX__,________,
  _XXXXX__,____XXXX,XXXXXX__,________,
  __XXX___,____XXXX,XXXX____,________,
  ___X____,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti20_6740[104] = { /* code 6740 */
  ____XX__,________,___X____,________,
  ___XXXXX,________,_XXXXX__,________,
  ____XXXX,XX______,XXXXX___,________,
  _____XXX,XXXX__XX,XXXX____,________,
  _______X,XXXXXXXX,XX______,________,
  ________,XXXXXXXX,X_______,________,
  _______X,XXXXXXXX,XXX_____,________,
  ____XXXX,XXXXXXXX,XXXXXX__,________,
  _XXXXXXX,XX_____X,XXXXXXX_,________,
  __XXXXXX,________,__XXXXX_,________,
  ___XX___,___XXXX_,____XX__,________,
  ________,___XXXX_,________,________,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,________,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,________,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,________,
  ________,___XXXX_,________,________,
  ________,___XXXX_,________,________,
  ______XX,___XXXX_,_XX_____,________,
  _____XXX,X__XXXX_,XXXXX___,________,
  ___XXXXX,___XXXX_,_XXXXX__,________,
  _XXXXXX_,___XXXX_,__XXXXXX,________,
  XXXXXX__,___XXXX_,____XXXX,X_______,
  _XXX____,___XXXX_,_____XXX,X_______,
  _XX___XX,XXXXXX__,_______X,________,
  _______X,XXXXXX__,________,________,
  _______X,XXXXX___,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti20_7206[104] = { /* code 7206 */
  ____XXX_,________,________,________,
  ____XXX_,_XXXXXXX,XXXXXXXX,X_______,
  ____XXX_,_XXXXXXX,XXXXXXXX,X_______,
  ____XXX_,_XXX____,______XX,X_______,
  ____XXX_,_XXXXXXX,XXXXXXXX,X_______,
  XXX_XXXX,XXXXXXXX,XXXXXXXX,X_______,
  _XX_XXXX,XXXX____,______XX,X_______,
  _XX_XXXX,XXXXXXXX,XXXXXXXX,X_______,
  _XX_XXXX,_XXXXXXX,XXXXXXXX,X_______,
  _XX_XXXX,____XXX_,___XXX__,________,
  _XX_XXX_,_XXXXXXX,XXXXXXXX,X_______,
  _XX_XXX_,_XXXXXXX,XXXXXXXX,X_______,
  ____XXX_,____XXX_,___XXX__,________,
  ____XXX_,XXXXXXXX,XXXXXXXX,XX______,
  ____XXX_,XXXXXXXX,XXXXXXXX,XX______,
  ____XX__,___XXXX_,___XXX__,________,
  ___XXXX_,__XXXX__,XXX_XXX_,________,
  ___XXXXX,_XXXXXX_,XXX_XXXX,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,X_______,
  ___XXXXX,XXXX_XX_,XXX_XXXX,XXX_____,
  __XXX_XX,XX___XX_,XXX_X__X,XX______,
  __XXX___,___XXXX_,XXXXXXX_,X_______,
  _XXXX___,_XXXXXXX,XXX_XXXX,X_______,
  _XXX____,XXXXX___,XXX___XX,XX______,
  _XXX____,_XX__XXX,XX_____X,X_______,
  __X_____,_____XXX,X_______,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti20_836F[100] = { /* code 836F */
  _______X,XXX_____,XXXX____,________,
  _______X,XXX_____,XXXX____,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  _______X,XXX_____,XXXX____,________,
  _____XXX,XXX_____,XXXX____,________,
  ____XXXX,______XX,________,________,
  ____XXX_,_____XXX,X_______,________,
  ___XXX__,XX___XXX,XXXXXXXX,XX______,
  __XXX__X,XXXXXXXX,XXXXXXXX,XX______,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  _XXXXXXX,XXXXXXX_,______XX,XX______,
  _XXXXXXX,X_XXXX_X,______XX,XX______,
  ____XXXX,____X_XX,X_____XX,XX______,
  ___XXXX_,_XX___XX,XX____XX,XX______,
  __XXXXXX,XXX____X,XXX___XX,XX______,
  __XXXXXX,XXX_____,XXX___XX,X_______,
  __XXXXXX,XXX_____,XXX___XX,X_______,
  __XXXXX_,________,_X____XX,X_______,
  ________,________,______XX,X_______,
  _____XXX,XXX_____,_____XXX,X_______,
  _XXXXXXX,XXX____X,XXXXXXXX,X_______,
  __XXXXXX,XXX____X,XXXXXXXX,X_______,
  __XXXX__,_______X,XXXXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti20_8840[100] = { /* code 8840 */
  ________,__XXX___,________,________,
  ________,__XXXX__,________,________,
  ________,_XXXXX__,________,________,
  ________,_XXXX___,________,________,
  __XXXXXX,XXXXXXXX,XXXXXXX_,________,
  __XXXXXX,XXXXXXXX,XXXXXXX_,________,
  __XXXXXX,XXXXXXXX,XXXXXXX_,________,
  __XXX___,XXX___XX,X___XXX_,________,
  __XXX___,XXX___XX,X___XXX_,________,
  __XXX___,XXX___XX,X___XXX_,________,
  __XXX___,XXX___XX,X___XXX_,________,
  __XXX___,XXX___XX,X___XXX_,________,
  __XXX___,XXX___XX,X___XXX_,________,
  __XXX___,XXX___XX,X___XXX_,________,
  __XXX___,XXX___XX,X___XXX_,________,
  __XXX___,XXX___XX,X___XXX_,________,
  __XXX___,XXX___XX,X___XXX_,________,
  __XXX___,XXX___XX,X___XXX_,________,
  __XXX___,XXX___XX,X___XXX_,________,
  __XXX___,XXX___XX,X___XXX_,________,
  __XXX___,XXX___XX,X___XXX_,________,
  __XXX___,XXX___XX,X___XXX_,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,X_______,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,X_______,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti20_88AB[104] = { /* code 88AB */
  _____X__,________,_XXX____,________,
  ___XXXX_,________,_XXX____,________,
  ___XXXX_,________,_XXX____,________,
  ____XXXX,___XXXXX,XXXXXXXX,XX______,
  ____XXXX,___XXXXX,XXXXXXXX,XX______,
  _____XX_,___XXXXX,XXXXXXXX,XX______,
  _XXXXXXX,X__XXX__,_XXX___X,XX______,
  _XXXXXXX,X__XXX__,_XXX___X,XX______,
  _XXXXXXX,X__XXX__,_XXX__XX,XX______,
  _____XXX,___XXX__,_XXX__XX,XX______,
  ____XXXX,___XXX__,_XXX____,________,
  ___XXXX_,___XXXXX,XXXXXXXX,XX______,
  ___XXXX_,XX_XXXXX,XXXXXXXX,XX______,
  __XXXX__,XXXXXXXX,XXXXXXXX,XX______,
  _XXXXX_X,XX_XXX__,X_____XX,X_______,
  XXXXXXXX,X_XXXXXX,X____XXX,X_______,
  _XXXXXXX,X_XXXXXX,XX___XXX,X_______,
  _XXXXX_X,XXXXXX_X,XXX_XXXX,________,
  _X_XXX__,XXXXXX_X,XXXXXXX_,________,
  ___XXX__,X_XXX___,XXXXXXX_,________,
  ___XXX__,__XXX___,_XXXXX__,________,
  ___XXX__,_XXXX__X,XXXXXXX_,________,
  ___XXX__,_XXXXXXX,XXXXXXXX,X_______,
  ___XXX__,XXXXXXXX,XXX_XXXX,XX______,
  ___XXX__,_XXX_XXX,X____XXX,XX______,
  ___XXX__,___X__X_,_______X,X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fontsongti20_91CF[ 96] = { /* code 91CF */
  ___XXXXX,XXXXXXXX,XXXXXXXX,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,________,
  ___XXXX_,________,____XXXX,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,________,
  ___XXXX_,________,____XXXX,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,________,
  ________,________,________,________,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  ________,________,________,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,________,
  ___XXX__,____XXX_,_____XXX,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,________,
  ___XXX__,____XXX_,_____XXX,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,________,
  ________,____XXX_,________,________,
  __XXXXXX,XXXXXXXX,XXXXXXXX,X_______,
  __XXXXXX,XXXXXXXX,XXXXXXXX,X_______,
  ________,____XXX_,________,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_Fontsongti20_CharInfo[23] = {
   {   1,   1,   0,  29,   8, acGUI_Fontsongti20_0020 } /* code 0020, SPACE */
  ,{  15,  20,   1,   9,  17, acGUI_Fontsongti20_0030 } /* code 0030, DIGIT ZERO */
  ,{  12,  20,   3,   9,  17, acGUI_Fontsongti20_0031 } /* code 0031, DIGIT ONE */
  ,{  13,  20,   2,   9,  17, acGUI_Fontsongti20_0032 } /* code 0032, DIGIT TWO */
  ,{  13,  20,   2,   9,  17, acGUI_Fontsongti20_0033 } /* code 0033, DIGIT THREE */
  ,{  15,  20,   1,   9,  17, acGUI_Fontsongti20_0034 } /* code 0034, DIGIT FOUR */
  ,{  13,  20,   2,   9,  17, acGUI_Fontsongti20_0035 } /* code 0035, DIGIT FIVE */
  ,{  15,  20,   1,   9,  17, acGUI_Fontsongti20_0036 } /* code 0036, DIGIT SIX */
  ,{  15,  20,   1,   9,  17, acGUI_Fontsongti20_0037 } /* code 0037, DIGIT SEVEN */
  ,{  15,  20,   1,   9,  17, acGUI_Fontsongti20_0038 } /* code 0038, DIGIT EIGHT */
  ,{  14,  20,   1,   9,  17, acGUI_Fontsongti20_0039 } /* code 0039, DIGIT NINE */
  ,{  27,  26,   0,   7,  27, acGUI_Fontsongti20_4EBA } /* code 4EBA */
  ,{  25,  26,   1,   7,  27, acGUI_Fontsongti20_5934 } /* code 5934 */
  ,{  26,  26,   1,   7,  27, acGUI_Fontsongti20_5F39 } /* code 5F39 */
  ,{  27,  26,   0,   7,  27, acGUI_Fontsongti20_6211 } /* code 6211 */
  ,{  27,  26,   0,   7,  27, acGUI_Fontsongti20_654C } /* code 654C */
  ,{  26,  26,   0,   7,  27, acGUI_Fontsongti20_65B9 } /* code 65B9 */
  ,{  25,  26,   1,   6,  27, acGUI_Fontsongti20_6740 } /* code 6740 */
  ,{  27,  26,   0,   7,  27, acGUI_Fontsongti20_7206 } /* code 7206 */
  ,{  27,  25,   0,   6,  27, acGUI_Fontsongti20_836F } /* code 836F */
  ,{  25,  25,   1,   7,  27, acGUI_Fontsongti20_8840 } /* code 8840 */
  ,{  27,  26,   0,   7,  27, acGUI_Fontsongti20_88AB } /* code 88AB */
  ,{  27,  24,   0,   8,  27, acGUI_Fontsongti20_91CF } /* code 91CF */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontsongti20_Prop14 = {
   0x91CF /* first character */
  ,0x91CF /* last character  */
  ,&GUI_Fontsongti20_CharInfo[ 22] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontsongti20_Prop13 = {
   0x88AB /* first character */
  ,0x88AB /* last character  */
  ,&GUI_Fontsongti20_CharInfo[ 21] /* address of first character */
  ,&GUI_Fontsongti20_Prop14 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontsongti20_Prop12 = {
   0x8840 /* first character */
  ,0x8840 /* last character  */
  ,&GUI_Fontsongti20_CharInfo[ 20] /* address of first character */
  ,&GUI_Fontsongti20_Prop13 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontsongti20_Prop11 = {
   0x836F /* first character */
  ,0x836F /* last character  */
  ,&GUI_Fontsongti20_CharInfo[ 19] /* address of first character */
  ,&GUI_Fontsongti20_Prop12 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontsongti20_Prop10 = {
   0x7206 /* first character */
  ,0x7206 /* last character  */
  ,&GUI_Fontsongti20_CharInfo[ 18] /* address of first character */
  ,&GUI_Fontsongti20_Prop11 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontsongti20_Prop9 = {
   0x6740 /* first character */
  ,0x6740 /* last character  */
  ,&GUI_Fontsongti20_CharInfo[ 17] /* address of first character */
  ,&GUI_Fontsongti20_Prop10 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontsongti20_Prop8 = {
   0x65B9 /* first character */
  ,0x65B9 /* last character  */
  ,&GUI_Fontsongti20_CharInfo[ 16] /* address of first character */
  ,&GUI_Fontsongti20_Prop9 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontsongti20_Prop7 = {
   0x654C /* first character */
  ,0x654C /* last character  */
  ,&GUI_Fontsongti20_CharInfo[ 15] /* address of first character */
  ,&GUI_Fontsongti20_Prop8 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontsongti20_Prop6 = {
   0x6211 /* first character */
  ,0x6211 /* last character  */
  ,&GUI_Fontsongti20_CharInfo[ 14] /* address of first character */
  ,&GUI_Fontsongti20_Prop7 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontsongti20_Prop5 = {
   0x5F39 /* first character */
  ,0x5F39 /* last character  */
  ,&GUI_Fontsongti20_CharInfo[ 13] /* address of first character */
  ,&GUI_Fontsongti20_Prop6 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontsongti20_Prop4 = {
   0x5934 /* first character */
  ,0x5934 /* last character  */
  ,&GUI_Fontsongti20_CharInfo[ 12] /* address of first character */
  ,&GUI_Fontsongti20_Prop5 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontsongti20_Prop3 = {
   0x4EBA /* first character */
  ,0x4EBA /* last character  */
  ,&GUI_Fontsongti20_CharInfo[ 11] /* address of first character */
  ,&GUI_Fontsongti20_Prop4 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontsongti20_Prop2 = {
   0x0030 /* first character */
  ,0x0039 /* last character  */
  ,&GUI_Fontsongti20_CharInfo[  1] /* address of first character */
  ,&GUI_Fontsongti20_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_Fontsongti20_Prop1 = {
   0x0020 /* first character */
  ,0x0020 /* last character  */
  ,&GUI_Fontsongti20_CharInfo[  0] /* address of first character */
  ,&GUI_Fontsongti20_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_Fontsongti20 = {
   GUI_FONTTYPE_PROP_EXT /* type of font    */
  ,36 /* height of font  */
  ,36 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Fontsongti20_Prop1}
  ,29 /* Baseline */
  ,15 /* Height of lowercase characters */
  ,20 /* Height of capital characters */
};

